name: CloneableItem
version: '${project.version}'
main: thedavid.cloneableitem.CloneableItem
api-version: '1.20'
commands:
    cloneitem:
        description: Clones the item in your hand
        usage: /<command>
        permission: cloneitem.use
        aliases: [ci]
